# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_company',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_schedule',
            fields=[
                ('bus_schedule_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_time_arrive', models.DateTimeField()),
                ('date_time_depart', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('bus_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_card', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('license', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id_card', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('company_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Bus_company')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='province_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Province'),
        ),
        migrations.AddField(
            model_name='drive',
            name='id_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Driver'),
        ),
        migrations.AddField(
            model_name='bus_schedule',
            name='platform_id_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='brs_cmu.Platform'),
        ),
        migrations.AddField(
            model_name='bus_schedule',
            name='platform_id_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='brs_cmu.Platform'),
        ),
        migrations.AddField(
            model_name='bus',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Bus_company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_schedule_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Bus_schedule'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brs_cmu.Passenger'),
        ),
        migrations.AlterUniqueTogether(
            name='phoneno',
            unique_together=set([('phone_no', 'company_name')]),
        ),
    ]
