# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-17 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs_cmu', '0003_auto_20160415_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bus_schedule',
            unique_together=set([('bus_id', 'platform_id_origin', 'date_time_arrive', 'platform_id_destination', 'date_time_depart')]),
        ),
    ]
