# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs_cmu', '0004_auto_20160417_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_no',
            field=models.IntegerField(default=0),
        ),
    ]
