# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs_cmu', '0005_passenger_seat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(default=0),
        ),
    ]
