# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('idetification_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('license', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('bus_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('idetification_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
