# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact',
            field=models.TextField(),
        ),
    ]
