# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160312_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
