# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_company',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount_of_bus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('platform', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('company_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus_company')),
                ('id_bus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
            ],
        ),
    ]
