# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reserve_seat', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_company',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount_of_bus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
                ('platform', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('bus_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
                ('company_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus_company')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('company_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus_company')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.Bus_company'),
        ),
        migrations.AlterUniqueTogether(
            name='phoneno',
            unique_together=set([('phone_no', 'company_name')]),
        ),
    ]
